export const multiStepFormData = [
  {
    id: 1,
    name: "Personal Info",
    fields: [
      {
        name: "name",
        label: "Name",
        type: "text",
        value: "",
        placeholder: "Name",
        required: true,
        disabled: false,
        title: "name",
        size: "L",
        validation: ["empty", "name"],
        defaultValue: "",
        tooltipText: "Enter your full name",
        icon: "user",
        mask: null,
        conditionalVisibility: null,
        autocomplete: "name",
        options: [],
      },
      {
        name: "email",
        label: "Email",
        type: "text",
        value: "",
        placeholder: "Email",
        required: true,
        disabled: false,
        title: "Email",
        size: "L",
        validation: ["empty", "email"],
        defaultValue: "",
        tooltipText: "Enter your email address",
        icon: "mail",
        mask: null,
        conditionalVisibility: null,
        autocomplete: "email",
        options: [],
      },
      {
        name: "phonenumber",
        label: "Phone Number",
        type: "text",
        value: "",
        placeholder: "Phone Number",
        required: true,
        disabled: false,
        title: "Phone Number",
        size: "L",
        validation: ["empty", "phonenumber"],
        defaultValue: "",
        tooltipText: "Enter your phone number",
        icon: "phone",
        mask: "+99-9999999999",
        conditionalVisibility: null,
        autocomplete: "tel",
        options: [],
      },
    ],
  },
  {
    id: 2,
    name: "Address",
    fields: [
      {
        name: "street",
        label: "Street",
        type: "text",
        value: "",
        placeholder: "Street",
        required: true,
        disabled: false,
        title: "Street",
        size: "L",
        validation: ["empty"],
        defaultValue: "",
        tooltipText: "Enter your street address",
        icon: "map",
        mask: null,
        conditionalVisibility: null,
        autocomplete: "street-address",
        options: [],
      },
      {
        name: "city",
        label: "City",
        type: "text",
        value: "",
        placeholder: "City",
        required: true,
        disabled: false,
        title: "City",
        size: "L",
        validation: ["empty"],
        defaultValue: "",
        tooltipText: "Enter your city",
        icon: "building",
        mask: null,
        conditionalVisibility: null,
        autocomplete: "address-level2",
        options: [],
      },
      {
        name: "state",
        label: "State",
        type: "text",
        value: "",
        placeholder: "State",
        required: true,
        disabled: false,
        title: "State",
        size: "L",
        validation: ["empty"],
        defaultValue: "",
        tooltipText: "Enter your state",
        icon: "flag",
        mask: null,
        conditionalVisibility: null,
        autocomplete: "address-level1",
        options: [],
      },
      {
        name: "zip",
        label: "Zip",
        type: "text",
        value: "",
        placeholder: "Zip",
        required: true,
        disabled: false,
        title: "Zip",
        size: "L",
        validation: ["empty", "zip"],
        defaultValue: "",
        tooltipText: "Enter your zip code",
        icon: "hash",
        mask: "99999",
        conditionalVisibility: null,
        autocomplete: "postal-code",
        options: [],
      },
      {
        name: "country",
        label: "Country",
        type: "text",
        value: "",
        placeholder: "Country",
        required: true,
        disabled: false,
        title: "Country",
        size: "L",
        validation: ["empty"],
        defaultValue: "",
        tooltipText: "Enter your country",
        icon: "globe",
        mask: null,
        conditionalVisibility: null,
        autocomplete: "country-name",
        options: [],
      },
    ],
  },
  {
    id: 3,
    name: "Confirm",
    fields: [
      {
        name: "password",
        label: "Password",
        type: "password",
        value: "",
        placeholder: "Enter password",
        required: true,
        disabled: false,
        title: "Password",
        size: "L",
        validation: ["empty", "password"],
        defaultValue: "",
        tooltipText: "Enter a secure password",
        icon: "lock",
        mask: null,
        conditionalVisibility: null,
        autocomplete: "new-password",
        options: [],
      },
      {
        name: "confirmPassword",
        label: "Confirm Password",
        type: "password",
        value: "",
        placeholder: "Confirm password",
        required: true,
        disabled: false,
        title: "Confirm Password",
        size: "L",
        validation: ["empty", "confirmPassword"],
        defaultValue: "",
        tooltipText: "Re-enter your password",
        icon: "lock-check",
        mask: null,
        conditionalVisibility: null,
        autocomplete: "new-password",
        options: [],
      },
      {
        name: "consent",
        label: "I agree to the Terms and Conditions",
        type: "checkbox",
        value: false,
        placeholder: "",
        required: true,
        disabled: false,
        title: "Consent",
        size: "L",
        validation: ["checked"],
        defaultValue: false,
        tooltipText: "You must agree before submitting",
        icon: "check-square",
        mask: null,
        conditionalVisibility: null,
        autocomplete: null,
        options: [],
      },
    ],
  },
  {
    id: 4,
    name: "Job Details",
    fields: [
      {
        name: "jobTitle",
        label: "Job Title",
        type: "text",
        value: "",
        placeholder: "Enter job title",
        required: true,
        disabled: false,
        title: "Job Title",
        size: "L",
        validation: ["empty"],
        tooltipText: "Enter the title for the job",
        icon: "briefcase",
        autocomplete: "off",
        options: [],
      },
      {
        name: "jobType",
        label: "Job Type",
        type: "select",
        value: "",
        placeholder: "Select job type",
        required: true,
        title: "Job Type",
        validation: ["empty"],
        tooltipText: "Select job type from API",
        icon: "chevron-down",
        options: "API: /api/job-types", // dropdown from API
      },
      {
        name: "tags",
        label: "Tags",
        type: "multiselect",
        value: [],
        placeholder: "Select relevant tags",
        required: true,
        title: "Tags",
        validation: ["empty"],
        tooltipText: "Select multiple tags from API",
        icon: "tag",
        options: "API: /api/tags", // multiselect dropdown from API
      },
      {
        name: "experienceLevel",
        label: "Experience Level",
        type: "radio",
        value: "",
        required: true,
        title: "Experience Level",
        validation: ["empty"],
        tooltipText: "Select experience level",
        icon: "sliders",
        options: [
          { label: "Junior", value: "junior" },
          { label: "Mid", value: "mid" },
          { label: "Senior", value: "senior" },
        ],
      },
      {
        name: "createdAt",
        label: "Created At",
        type: "date",
        value: "",
        placeholder: "Select creation date",
        required: true,
        disabled: false,
        title: "Created At",
        size: "L",
        validation: ["empty", "date"],
        defaultValue: "",
        tooltipText: "Date this record was created",
        icon: "calendar-plus",
        mask: null,
        conditionalVisibility: null,
        autocomplete: "off",
        options: [],
      },
    ],
  },
  {
    id: 5,
    name: "Preferences",
    fields: [
      {
        name: "locationPreference",
        label: "Location",
        type: "select",
        value: "",
        placeholder: "Select location",
        required: true,
        title: "Location",
        validation: ["empty"],
        tooltipText: "Choose location from static list",
        icon: "map-pin",
        options: [
          { label: "Remote", value: "remote" },
          { label: "On-site", value: "onsite" },
          { label: "Hybrid", value: "hybrid" },
        ],
      },
      {
        name: "skills",
        label: "Required Skills",
        type: "multiselect",
        value: [],
        placeholder: "Select required skills",
        required: true,
        title: "Skills",
        validation: ["empty"],
        tooltipText: "Choose required skills",
        icon: "code",
        options: [
          { label: "JavaScript", value: "js" },
          { label: "Python", value: "python" },
          { label: "Go", value: "go" },
          { label: "Rust", value: "rust" },
        ],
      },
      {
        name: "preferredLanguages",
        label: "Preferred Languages",
        type: "multiselect",
        value: [],
        placeholder: "Select preferred languages",
        required: true,
        title: "Languages",
        validation: ["empty"],
        tooltipText: "Choose preferred languages from API",
        icon: "globe",
        options: "API: /api/languages", // multiselect dropdown from API
      },
      {
        name: "salaryRange",
        label: "Salary Range",
        type: "select",
        value: "",
        placeholder: "Select range",
        required: true,
        title: "Salary",
        validation: ["empty"],
        tooltipText: "Choose your salary expectation",
        icon: "dollar-sign",
        options: [
          { label: "$40k - $60k", value: "40-60" },
          { label: "$60k - $80k", value: "60-80" },
          { label: "$80k - $100k", value: "80-100" },
        ],
      },
      {
        name: "updatedAt",
        label: "Updated At",
        type: "date",
        value: "",
        placeholder: "Select update date",
        required: true,
        disabled: false,
        title: "Updated At",
        size: "L",
        validation: ["empty", "date"],
        defaultValue: "",
        tooltipText: "Date this record was last updated",
        icon: "calendar-check",
        mask: null,
        conditionalVisibility: null,
        autocomplete: "off",
        options: [],
      },
    ],
  },
  {
    id: 6,
    name: "Search Metadata",
    fields: [
      {
        name: "keywords",
        label: "Search Keywords",
        type: "typeahead",
        value: "",
        placeholder: "Start typing...",
        required: true,
        title: "Keywords",
        validation: ["empty"],
        tooltipText: "Enter keywords (auto-suggest)",
        icon: "search",
        options: "API: /api/search-keywords", // complete typeahead
      },
      {
        name: "employmentType",
        label: "Employment Type",
        type: "select",
        value: "",
        placeholder: "Select employment type",
        required: true,
        title: "Employment",
        validation: ["empty"],
        tooltipText: "Choose employment type",
        icon: "briefcase",
        options: [
          { label: "Full-time", value: "full-time" },
          { label: "Part-time", value: "part-time" },
          { label: "Contract", value: "contract" },
        ],
      },
      {
        name: "workEnvironment",
        label: "Work Environment",
        type: "multiselect",
        value: [],
        placeholder: "Select work environments",
        required: true,
        title: "Environment",
        validation: ["empty"],
        tooltipText: "Select environments",
        icon: "layers",
        options: [
          { label: "Startup", value: "startup" },
          { label: "Corporate", value: "corporate" },
          { label: "Agency", value: "agency" },
          { label: "Non-profit", value: "nonprofit" },
        ],
      },
      {
        name: "benefits",
        label: "Benefits",
        type: "multiselect",
        value: [],
        placeholder: "Select benefits",
        required: true,
        title: "Benefits",
        validation: ["empty"],
        tooltipText: "Choose available benefits",
        icon: "gift",
        options: "API: /api/benefits", // multiselect from API
      },
      {
        name: "jobStatus",
        label: "Job Status",
        type: "radio",
        value: "",
        required: true,
        title: "Status",
        validation: ["empty"],
        tooltipText: "Choose current job status",
        icon: "activity",
        options: [
          { label: "Open", value: "open" },
          { label: "Closed", value: "closed" },
          { label: "Paused", value: "paused" },
        ],
      },
    ],
  },
];

export const formJson = {
  multilingualFields: ["name"],
  form: multiStepFormData,
};
